export const jobLocation = ["Remote", "in Office"];
export const jobRoles = [
  "Backend",
  "Frontend",
  "Fullstack",
  "IOS",
  "Flutter",
  "React Native",
  "Android",
  "Tech Lead",
  "Dev-Ops",
  "Data Engineer",
  "Data Science",
  "Computer Vision",
  "Nlp",
  "Deep Learning",
  "Test / Qa",
  "Web3",
  "Sre",
  "Data Infrastructure",
  "Designer",
  "Design Manager",
  "Graphic Designer",
  "Product Designer",
  "Product Manager",
  "Operations Manager",
  "Founder's Office/ Chief of staffs",
  "Sales Development Representative",
  "Account Executive",
  "Account Manager",
  "Digital Marketing Manager",
  "Growth Hacker",
  "Marketing",
  "Product Marketing Manager",
  "Hardware",
  "Mechanical",
  "Systems",
  "Business Analyst",
  "Data Analyst",
  "Project Manager",
  "Management",
  "Legal",
  "HR",
  "Finance",
];

export const minExperience = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
];

export const minBasePay = [
  "0L",
  "10L",
  "20L",
  "30L",
  "40L",
  "50L",
  "60L",
  "70L",
];
